realsense:
  ros__parameters:
    camera_name: realsense
    enable_accel: true
    pointcloud.enable: true
    accel_qos: SENSOR_DATA
    color_qos: SENSOR_DATA
    depth_qos: SENSOR_DATA
    pointcloud.pointcloud_qos: SENSOR_DATA
