yolo_detector:
  ros__parameters:
    image_topics:
      - /realsense/color/image_raw
      - /camera/image_rotated
    model_conf_threshold: 0.6
    model_iou_threshold: 0.5
    model_image_size: "416"
