darknet_ros:
  ros__parameters:
    yolo_model:
      config_file:
        name: vidvipo-yolov2-tiny.cfg
      weight_file:
        name: vidvipo-yolov2-tiny.weights
      threshold:
        value: 0.3
      detection_classes:
        names:
          - person
          - bicycle
          - car
          - motorbike
          - bus
          - train
          - truck
          - boat
          - traffic_light
          - bicycler
          - braille_block
          - guardrail
          - white_line
          - crosswalk
          - signal_button
          - signal_red
          - signal_blue
          - stairs
          - handrail
          - steps
          - faregates
          - train_ticket_machine
          - shrubs
          - tree
          - vending_machine
          - bathroom
          - door
          - elevator
          - escalator
          - bollard
          - bus_stop_sign
          - pole
          - monument
          - fence
          - wall
          - signboard
          - flag
          - postbox
          - safety-cone
